name: Auto Update Toffee Streams

on:
  schedule:
    - cron: '*/30 * * * *' # প্রতি ৩০ মিনিটে আপডেট হবে
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Toffee Scraper
        run: python update_toffee.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add toffee_channel_data.json toffee_playlist.m3u
          # যদি কোনো পরিবর্তন থাকে তবেই কমিট করবে
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto Update Toffee Playlist: Fresh Cookies Added" && git push)
